#ifndef EFFECT_SETTINGS_H
#define EFFECT_SETTINGS_H

#include <Arduino.h>

const int NumberOfAllowedEffectsToPickBetween = 20;
const int NumberOfAllowedPalettesToPickBetween = 5;

typedef struct
{
  byte LikelihoodEffectsAreRandomizedWhenBeatDetected;
  byte LikelihoodEffectsAreRandomizedWhenAntiBeatDetected;
  byte LikelihoodEffectsAreRandomizedWhenBeatDetectorReturnsToZero;
  byte LikelihoodEffectsAreRandomizedWhenStepIsDetected;

  byte LikelihoodNothingChangesWhenRandomizingEffect;
  byte LikelihoodBlendingModeChangesWhenRandomizingEffect;
  byte LikelihoodSubPaletteChangesWhenRandomizingEffect;
  byte LikelihoodPaletteChangesWhenRandomizingEffect;
  byte LikelihoodTwoPalettesAreUsedWhenPaletteChanges;

  byte LikelihoodBackgroundTransitionTimeChangesWhenRandomizingEffect;
  byte LikelihoodScreenMapChangesWhenRandomizingEffect;
  byte LikelihoodEffectsAreSwappedWhenRandomizingEffect;
  byte LikelihoodTransformMapsAreSwitchedWhenEffectsAreSwapped;
  byte LikelihoodAnyIndividualTransformMapChangesWhenTransformMapsAreSwitched;
  byte LikelihoodTransformMapsAreRandomizedWithoutFadeWhenRandomizingEffect;
  byte LikelihoodAnyIndividualTransformMapChangesWhenTransformMapsAreRandomized;

  byte LikelihoodTimeModesRandomizeWhenRandomizingEffect;
  byte LikelihoodAnyIndividualTimeModeChangesWhenTimeModeRandomizes;

  byte LikelihoodEffectsAndRandomizedWhenRandomizingEffect;

  byte LikelihoodSizeParameterForEffectsChangesWhenWhenRandomizingEffect;

  byte LikelihoodGlobalBrightnessModesChangeWhenRandomizingEffect;
  byte LikelihoodIndividualGlobalBrightnessModesChange;

  byte LikelihoodTransitionDirectionChangesWhenRandomizingEffect;

  byte LikelihoodMovementBasedBrightnessModeIsPicked;
  byte LikelihoodMusicBasedBrightnessModeIsPicked;
  byte LikelihoodMovementBasedTimeModeIsPicked;
  
  uint16_t MillisecondToMoveToNextPaletteFrame;
  uint16_t MillisecondsForEffectTransitionsMinimum;
  uint16_t MillisecondsForEffectTransitionsMaximum;
  uint16_t MillisecondsForBlendingModeTransitionsMinimum;
  uint16_t MillisecondsForBlendingModeTransitionsMaximum;

  uint16_t MillisecondsForBackgroundTransitionFadeMinimum;
  uint16_t MillisecondsForBackgroundTransitionFadeMaximum;

  uint16_t GlobalPercentOfLastFrameToUseWhenNotSwitchingTransformMaps;
  uint16_t GlobalPercentOfLastFrameToUseWhenSwitchingTransformMaps;

  byte LikelihoodAudioLevelThresholdsForMoreIntenseEffectChangeWhenRandomizingEffect;
  uint16_t AudioLevelThresholdToShowMoreIntenseEffectMinimum;
  uint16_t AudioLevelThresholdToShowMoreIntenseEffectMaximum;

  byte AllowedEffects[NumberOfAllowedEffectsToPickBetween];
  byte AllowedPalettes[NumberOfAllowedPalettesToPickBetween][NumberOfAllowedPalettesToPickBetween + 1];

  byte MinimumEffectSize;
  byte MaximumEffectSize;

  byte LikelihoodWingsAreMirroredWhenTransformMapsAreRandomized;
}
EffectSettings;

#endif